### ISSUE TITLE
Xcode8 报错怎么处理？

### ISSUE THREAD

**Issue by iHTCboy** [hrscy/DanTang#3]
SwiftyJSON will not be code signed because its settings don't specify a development team.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by Drshu** [comment]
更换`SwiftJson`的版本为2.4.0，同时把所有的框架和项目本身的building setting里搜索`SWIFT_VERSION`，将所有的框架和项目本身`Use Legacy Swift Language Version`选项设置为Yes

**Comment by iHTCboy** [comment]
@Drshu  Thank you!

**Comment by Abel94** [comment]
xcode 8 里 alamofire 报错，

![Uploading FCA992BF-5AE4-48B6-B2E0-9448A004B89E.png…]()
