### ISSUE TITLE
新版首页分组列表

### ISSUE THREAD

**Issue by TokyJiao** [hrscy/DanTang#6]
您好，在使用你的代码来学习SWIFT，能实现一下新版的分组列表吗？

**Comment by hrscy** [comment]
新版的分组列表？有时间的话我会考虑实现的。非常感谢你的建议！

**Comment by TokyJiao** [comment]
谢谢你回复哟~~把你的代码当教材学习了~~看到单糖新版的首页内容能按时间来进行分组，希望能指导一下。先谢过~~~
