### ISSUE TITLE
好像内存有点小问题

### ISSUE THREAD

**Issue by LBBanner** [hrscy/DanTang#8]
hi，hrscy！
    我任意点击几个界面进去以后，打开内存Debug Memory Graph,会出现很多相关的内存问题，不知道是不是用了webview的原因？或者是其他内存方面的原因？如下图：
![image](https://user-images.githubusercontent.com/16589433/29346875-fdd351c4-827a-11e7-934d-dc4f0616ba09.png)

**Comment by hrscy** [comment]
可能是 webView，我尽快处理一下，感谢反馈！

**Comment by hrscy** [comment]
这是那个界面出现的问题？

**Comment by LBBanner** [comment]
好像和webview没有直接关系，进入app后就点了下面4个tabbar加载下界面就会出现这些提示。
![image](https://user-images.githubusercontent.com/16589433/29347617-6fc9095e-8280-11e7-89cc-411cb1c7f20e.png)

**Comment by LBBanner** [comment]
还想请问下，在oc中有PLeakSniffer类似的库可以辅助检测内存泄漏、循环引用问题，加上xcode自带的instument，但是在swift中貌似没看到有PLeakSniffer这种类似的库，不知道是楼主在swift中一般测内存泄漏是怎么弄的？

**Comment by hrscy** [comment]
类似库不太清楚，我用的instument还有 xcode8上的memory graph

**Comment by hrscy** [comment]
我运行了一下，并没有出现你图上的问题啊
