### ISSUE TITLE
首页滚动条

### ISSUE THREAD

**Issue by linbx08** [hrscy/DanTang#9]
hello, 作者代码写得不错,学习了. 个人小小建议 网络框架请求可以加入RxSwift, 直接用字典取其实容易崩溃 然后首页的滚动条如果不是写组件的话,个人建议可以写到BaseViewController里面. 这样结果更加清晰明了

**Comment by hrscy** [comment]
非常感谢你提的建议，但是现在这个项目目前不打算更新了。
我现在在写[另一个项目](https://github.com/hrscy/TodayNews)，在我的 github 上，但是最新版本还未上传，最新版本的代码使用 HandyJSON 这个框架来把 json 转成了 model，并且最新的代码中模型全部换成了 struct + protocol，更加 swift，但是目前还不会把最新代码上传，还需要过段时间，如果有兴趣可以关注。
